"""Scene state management for dynamic situation roleplay."""

from pydantic import BaseModel, Field


class SceneState(BaseModel):
    """Dynamic state of the roleplay scene, updated by the Narrator."""

    location: str = Field(description="Where the scene takes place")
    situation_summary: str = Field(description="Current state of what's happening")
    available_items: list[str] = Field(
        default_factory=list,
        description="Items/services currently available (if relevant to situation)",
    )
    current_challenges: list[str] = Field(
        default_factory=list,
        description="Active challenges or complications in the scene",
    )
    time_context: str = Field(default="", description="Time-related context")
    special_conditions: list[str] = Field(
        default_factory=list,
        description="Any special conditions affecting the scene",
    )


class NarratorEvent(BaseModel):
    """Event generated by the Narrator to change the situation."""

    updated_state: SceneState = Field(description="The new state of the scene")
    event_description_de: str = Field(
        description="German description of what happened (shown to user)"
    )
    event_context_for_npc: str = Field(
        description="English context for NPC about what changed and how to react"
    )
