"""Narrator agent that generates dynamic events during roleplay (like a DnD Game Master)."""

import os
from functools import cache

from google import genai
from pydantic import BaseModel, Field
from rich import print as rprint
from rich.panel import Panel
from rich.pretty import Pretty

from deutsch_tg_bot.config import settings
from deutsch_tg_bot.deutsh_enums import DeutschLevel
from deutsch_tg_bot.situation_training.scene_state import NarratorEvent, SceneState
from deutsch_tg_bot.situation_training.situations import Situation
from deutsch_tg_bot.utils.prompt_utils import (
    load_prompt_template_from_file,
    replace_promt_placeholder,
)

genai_client = genai.Client(api_key=settings.GOOGLE_API_KEY).aio

GOOGLE_MODEL = "gemini-2.5-flash"

PROMPTS_DIR = os.path.join(os.path.dirname(__file__), "prompts")

NARRATOR_TRIGGER_INTERVAL = 3


class InitialSceneState(BaseModel):
    """Initial scene state generated by narrator at start."""

    scene_state: SceneState = Field(description="Initial state of the scene")
    available_items_for_situation: list[str] = Field(
        default_factory=list,
        description="Relevant items/services available in this situation",
    )


async def generate_initial_scene_state(
    situation: Situation,
    level: DeutschLevel,
) -> SceneState:
    prompt_template = get_initial_scene_prompt_template()
    prompt = prompt_template % {
        "situation_name": situation.name_de,
        "character_role": situation.character_role,
        "user_role": situation.user_role_uk,
        "scenario_prompt": situation.scenario_prompt,
        "level": level.value,
    }

    response = await genai_client.models.generate_content(
        model=GOOGLE_MODEL,
        config=genai.types.GenerateContentConfig(
            response_mime_type="application/json",
            response_json_schema=InitialSceneState.model_json_schema(),
            temperature=0.7,
        ),
        contents=prompt,
    )

    response_text = (response.text or "").strip()

    initial_state = InitialSceneState.model_validate_json(response_text)
    scene_state = initial_state.scene_state
    if initial_state.available_items_for_situation:
        scene_state.available_items = initial_state.available_items_for_situation

    if settings.SHOW_FULL_AI_RESPONSE:
        rprint(
            Panel(
                Pretty(scene_state.model_dump(), expand_all=True),
                title="Initial Scene State",
                border_style="magenta",
            )
        )

    return scene_state


async def generate_narrator_event(
    situation: Situation,
    level: DeutschLevel,
    current_scene_state: SceneState,
    recent_dialogue: list[tuple[str, str]],
) -> NarratorEvent:
    system_prompt = get_narrator_system_prompt_template() % {
        "situation_name": situation.name_de,
        "character_role": situation.character_role,
        "level": level.value,
    }

    dialogue_text = "\n".join(f"- {role}: {message}" for role, message in recent_dialogue)

    event_prompt = get_narrator_event_prompt_template() % {
        "current_scene_state": current_scene_state.model_dump_json(indent=2),
        "recent_dialogue": dialogue_text,
    }

    response = await genai_client.models.generate_content(
        model=GOOGLE_MODEL,
        config=genai.types.GenerateContentConfig(
            system_instruction=system_prompt,
            response_mime_type="application/json",
            response_json_schema=NarratorEvent.model_json_schema(),
            temperature=0.8,
        ),
        contents=event_prompt,
    )

    response_text = (response.text or "").strip()
    narrator_event = NarratorEvent.model_validate_json(response_text)

    if settings.SHOW_FULL_AI_RESPONSE:
        rprint(
            Panel(
                Pretty(
                    {
                        "event_de": narrator_event.event_description_de,
                        "event_uk": narrator_event.event_description_uk,
                        "npc_context": narrator_event.event_context_for_npc,
                        "updated_state": narrator_event.updated_state.model_dump(),
                    },
                    expand_all=True,
                ),
                title="Narrator Event",
                border_style="magenta",
            )
        )

    return narrator_event


@cache
def get_narrator_system_prompt_template() -> str:
    return replace_promt_placeholder(
        load_prompt_template_from_file(PROMPTS_DIR, "narrator_system_prompt.txt")
    )


@cache
def get_narrator_event_prompt_template() -> str:
    return replace_promt_placeholder(
        load_prompt_template_from_file(PROMPTS_DIR, "narrator_event_prompt.txt")
    )


@cache
def get_initial_scene_prompt_template() -> str:
    return replace_promt_placeholder(
        load_prompt_template_from_file(PROMPTS_DIR, "initial_scene_prompt.txt")
    )


def should_trigger_narrator(message_count: int, last_narrator_index: int) -> bool:
    messages_since_narrator = message_count - last_narrator_index
    return messages_since_narrator >= NARRATOR_TRIGGER_INTERVAL
